import React, { useState, useEffect } from 'react';
import { 
  Building2, Users, DollarSign, TrendingUp, Award, AlertTriangle, 
  Search, ArrowUpDown, ChevronRight, Activity, ArrowUpRight, ArrowDownRight
} from 'lucide-react';
import { fetchOverview, fetchAcos } from '../api';

export default function ExecutiveCommandCenter({ onSelectAco }) {
  const [overview, setOverview] = useState(null);
  const [acosData, setAcosData] = useState(null);
  const [loading, setLoading] = useState(true);

  // Filter states
  const [track, setTrack] = useState('All');
  const [revCat, setRevCat] = useState('All');
  const [status, setStatus] = useState('All');
  const [riskFlag, setRiskFlag] = useState('All');
  const [search, setSearch] = useState('');
  const [sortBy, setSortBy] = useState('EarnSaveLoss');
  const [sortDesc, setSortDesc] = useState(true);
  const [page, setPage] = useState(1);
  const pageSize = 25;

  useEffect(() => {
    loadOverview();
  }, []);

  useEffect(() => {
    loadAcos();
  }, [track, revCat, status, riskFlag, search, sortBy, sortDesc, page]);

  async function loadOverview() {
    try {
      const data = await fetchOverview();
      setOverview(data);
    } catch (err) {
      console.error(err);
    }
  }

  async function loadAcos() {
    setLoading(true);
    try {
      const data = await fetchAcos({
        track,
        rev_cat: revCat,
        status,
        risk_flag: riskFlag,
        search,
        sort_by: sortBy,
        sort_desc: sortDesc,
        page,
        page_size: pageSize
      });
      setAcosData(data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  }

  const handleSort = (field) => {
    if (sortBy === field) {
      setSortDesc(!sortDesc);
    } else {
      setSortBy(field);
      setSortDesc(true);
    }
    setPage(1);
  };

  const kpis = overview?.kpis;

  return (
    <div>
      {/* View Header */}
      <div className="view-header">
        <div className="view-title-group">
          <h1>📊 Executive Command Center</h1>
          <p>CMS Medicare Shared Savings Program (MSSP) · Performance Year 2024 Contract Analytics</p>
        </div>
        <div className="header-badges">
          <span className="badge badge-success">● Published CMS PUF</span>
          <span className="badge badge-info">476 Verified ACOs</span>
        </div>
      </div>

      {/* KPI Row */}
      {kpis && (
        <div className="grid-kpis">
          <div className="kpi-card accent-sky">
            <div className="kpi-label">
              <span>Total Attributed Lives</span>
              <Users size={16} />
            </div>
            <div className="kpi-value">{kpis.total_beneficiaries.toLocaleString()}</div>
            <div className="kpi-sub">Across {kpis.total_acos} Participating ACOs</div>
          </div>

          <div className="kpi-card accent-emerald">
            <div className="kpi-label">
              <span>Total Earned Savings</span>
              <DollarSign size={16} />
            </div>
            <div className="kpi-value">${(kpis.total_earned_savings / 1e6).toFixed(1)}M</div>
            <div className="kpi-sub">Generated by high performers</div>
          </div>

          <div className="kpi-card accent-rose">
            <div className="kpi-label">
              <span>Total Shared Losses</span>
              <AlertTriangle size={16} />
            </div>
            <div className="kpi-value">${(kpis.total_losses / 1e6).toFixed(1)}M</div>
            <div className="kpi-sub">Under two-sided risk contracts</div>
          </div>

          <div className="kpi-card accent-emerald">
            <div className="kpi-label">
              <span>Net Program Savings</span>
              <TrendingUp size={16} />
            </div>
            <div className="kpi-value">${(kpis.net_savings / 1e6).toFixed(1)}M</div>
            <div className="kpi-sub">Avg Savings Rate: {kpis.avg_savings_rate}%</div>
          </div>

          <div className="kpi-card accent-amber">
            <div className="kpi-label">
              <span>Mean Quality Score</span>
              <Award size={16} />
            </div>
            <div className="kpi-value">{kpis.avg_quality_score}</div>
            <div className="kpi-sub">Mean Per-Capita: ${Math.round(kpis.avg_per_capita_exp).toLocaleString()}</div>
          </div>
        </div>
      )}

      {/* Filters Bar */}
      <div className="filter-bar">
        <div className="form-group input-with-icon" style={{ minWidth: '240px', flex: 1 }}>
          <Search size={16} className="input-icon" />
          <input
            type="text"
            className="input-text"
            placeholder="Search ACO by name or ID (e.g. A1001)..."
            value={search}
            onChange={(e) => { setSearch(e.target.value); setPage(1); }}
          />
        </div>

        <div className="form-group">
          <label className="form-label">Track</label>
          <select 
            className="select-input"
            value={track}
            onChange={(e) => { setTrack(e.target.value); setPage(1); }}
          >
            <option value="All">All Tracks</option>
            <option value="BASIC A">BASIC A</option>
            <option value="BASIC B">BASIC B</option>
            <option value="BASIC C">BASIC C</option>
            <option value="BASIC D">BASIC D</option>
            <option value="BASIC E">BASIC E</option>
            <option value="ENHANCED">ENHANCED</option>
          </select>
        </div>

        <div className="form-group">
          <label className="form-label">Revenue Tier</label>
          <select 
            className="select-input"
            value={revCat}
            onChange={(e) => { setRevCat(e.target.value); setPage(1); }}
          >
            <option value="All">All Tiers</option>
            <option value="Low Revenue">Low Revenue (Physician-Led)</option>
            <option value="High Revenue">High Revenue (Hospital-Led)</option>
          </select>
        </div>

        <div className="form-group">
          <label className="form-label">Savings Status</label>
          <select 
            className="select-input"
            value={status}
            onChange={(e) => { setStatus(e.target.value); setPage(1); }}
          >
            <option value="All">All Statuses</option>
            <option value="Earned Savings">Earned Savings</option>
            <option value="Loss">Loss</option>
            <option value="Break-even">Break-even</option>
          </select>
        </div>

        <div className="form-group">
          <label className="form-label">Risk Profile</label>
          <select 
            className="select-input"
            value={riskFlag}
            onChange={(e) => { setRiskFlag(e.target.value); setPage(1); }}
          >
            <option value="All">All Risk Profiles</option>
            <option value="Top Performer / Outperformer">Top Performer</option>
            <option value="Outperforming vs. peer profile">Outperforming</option>
            <option value="In line with peer profile">In Line</option>
            <option value="Underperforming vs. peer profile">Underperforming</option>
            <option value="High Risk Underperformer">High Risk Underperformer</option>
          </select>
        </div>

        {(track !== 'All' || revCat !== 'All' || status !== 'All' || riskFlag !== 'All' || search !== '') && (
          <button 
            className="btn btn-secondary"
            style={{ alignSelf: 'flex-end' }}
            onClick={() => {
              setTrack('All');
              setRevCat('All');
              setStatus('All');
              setRiskFlag('All');
              setSearch('');
              setPage(1);
            }}
          >
            Reset Filters
          </button>
        )}
      </div>

      {/* Visual Analytics Row: Cost vs Quality Quadrants & Leaderboard */}
      <div className="grid-2col">
        {/* Track Performance Matrix */}
        <div className="card">
          <div className="card-header">
            <div className="card-title">
              <Activity size={18} color="#38bdf8" />
              <span>Contract Performance by MSSP Track</span>
            </div>
            <span className="card-subtitle">Aggregated metrics by risk model</span>
          </div>

          <div className="table-container" style={{ border: 'none' }}>
            <table className="data-table">
              <thead>
                <tr>
                  <th>Track</th>
                  <th className="num">ACOs</th>
                  <th className="num">Attributed Lives</th>
                  <th className="num">Avg Savings Rate</th>
                  <th className="num">Total Earned</th>
                  <th className="num">Avg Quality</th>
                </tr>
              </thead>
              <tbody>
                {overview?.track_breakdown?.map((t) => (
                  <tr key={t.track} onClick={() => { setTrack(t.track); setPage(1); }}>
                    <td><strong style={{ color: 'var(--accent-sky)' }}>{t.track}</strong></td>
                    <td className="num">{t.count}</td>
                    <td className="num">{t.total_benes.toLocaleString()}</td>
                    <td className="num" style={{ color: t.avg_savings_rate >= 0 ? 'var(--status-success)' : 'var(--status-danger)' }}>
                      {t.avg_savings_rate.toFixed(2)}%
                    </td>
                    <td className="num" style={{ color: 'var(--status-success)' }}>
                      ${(t.total_earned / 1e6).toFixed(1)}M
                    </td>
                    <td className="num">{t.avg_quality.toFixed(1)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Savings & Loss Highlights */}
        <div className="card">
          <div className="card-header">
            <div className="card-title">
              <Award size={18} color="#10b981" />
              <span>Revenue Tier & Risk Model Dynamics</span>
            </div>
            <span className="card-subtitle">Physician-Led vs Hospital-Led Performance</span>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem', marginTop: '0.5rem' }}>
            {overview?.revenue_breakdown?.map((r) => (
              <div 
                key={r.category}
                style={{
                  background: 'var(--bg-surface-subtle)',
                  padding: '1rem',
                  borderRadius: 'var(--radius-sm)',
                  border: '1px solid var(--border-subtle)',
                  cursor: 'pointer'
                }}
                onClick={() => { setRevCat(r.category); setPage(1); }}
              >
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '0.5rem' }}>
                  <span style={{ fontWeight: 600, color: 'var(--text-primary)' }}>{r.category}</span>
                  <span className="badge badge-info">{r.count} ACOs</span>
                </div>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '0.5rem', fontSize: '0.8rem' }}>
                  <div>
                    <div style={{ color: 'var(--text-muted)' }}>Avg Savings Rate</div>
                    <div style={{ fontWeight: 700, color: r.avg_savings_rate >= 0 ? 'var(--status-success)' : 'var(--status-danger)' }}>
                      {r.avg_savings_rate.toFixed(2)}%
                    </div>
                  </div>
                  <div>
                    <div style={{ color: 'var(--text-muted)' }}>Total Earned Savings</div>
                    <div style={{ fontWeight: 700, color: 'var(--status-success)' }}>
                      ${(r.total_earned / 1e6).toFixed(1)}M
                    </div>
                  </div>
                  <div>
                    <div style={{ color: 'var(--text-muted)' }}>Mean Quality Score</div>
                    <div style={{ fontWeight: 700 }}>{r.avg_quality.toFixed(1)}</div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* ACO Master Table */}
      <div className="card">
        <div className="card-header">
          <div className="card-title">
            <Building2 size={18} color="#38bdf8" />
            <span>Participating ACO Roster</span>
          </div>
          <span className="card-subtitle">
            Showing {acosData?.acos?.length || 0} of {acosData?.total || 0} matching ACOs · Click any row to view 360° deep-dive
          </span>
        </div>

        {loading ? (
          <div className="loading-container">
            <div className="spinner"></div>
            <p>Loading ACO performance analytics...</p>
          </div>
        ) : (
          <div className="table-container">
            <table className="data-table">
              <thead>
                <tr>
                  <th onClick={() => handleSort('ACO_ID')}>
                    ACO ID <ArrowUpDown size={12} style={{ verticalAlign: 'middle' }} />
                  </th>
                  <th onClick={() => handleSort('ACO_Name')}>
                    ACO Name <ArrowUpDown size={12} style={{ verticalAlign: 'middle' }} />
                  </th>
                  <th>Track</th>
                  <th>Revenue Tier</th>
                  <th className="num" onClick={() => handleSort('N_AB')}>
                    Lives <ArrowUpDown size={12} style={{ verticalAlign: 'middle' }} />
                  </th>
                  <th className="num" onClick={() => handleSort('Per_Capita_Exp_TOTAL_PY')}>
                    Per-Capita Exp <ArrowUpDown size={12} style={{ verticalAlign: 'middle' }} />
                  </th>
                  <th className="num" onClick={() => handleSort('Sav_rate')}>
                    Savings Rate <ArrowUpDown size={12} style={{ verticalAlign: 'middle' }} />
                  </th>
                  <th className="num" onClick={() => handleSort('EarnSaveLoss')}>
                    Earned Savings/Loss <ArrowUpDown size={12} style={{ verticalAlign: 'middle' }} />
                  </th>
                  <th className="num" onClick={() => handleSort('QualScore')}>
                    Quality <ArrowUpDown size={12} style={{ verticalAlign: 'middle' }} />
                  </th>
                  <th>Risk Profile</th>
                  <th style={{ textAlign: 'center' }}>Action</th>
                </tr>
              </thead>
              <tbody>
                {acosData?.acos?.map((a) => {
                  const isPositive = a.EarnSaveLoss > 0;
                  const isLoss = a.EarnSaveLoss < 0;
                  return (
                    <tr key={a.ACO_ID} onClick={() => onSelectAco(a.ACO_ID)}>
                      <td className="mono" style={{ color: 'var(--accent-sky)', fontWeight: 600 }}>{a.ACO_ID}</td>
                      <td style={{ fontWeight: 600, maxWidth: '240px' }}>{a.ACO_Name}</td>
                      <td><span className="badge badge-neutral">{a.Current_Track}</span></td>
                      <td><span style={{ fontSize: '0.78rem', color: 'var(--text-secondary)' }}>{a.Rev_Exp_Cat}</span></td>
                      <td className="num">{Math.round(a.N_AB).toLocaleString()}</td>
                      <td className="num">${Math.round(a.Per_Capita_Exp_TOTAL_PY).toLocaleString()}</td>
                      <td className="num" style={{ 
                        fontWeight: 700, 
                        color: a.Sav_rate >= 0 ? 'var(--status-success)' : 'var(--status-danger)' 
                      }}>
                        {a.Sav_rate.toFixed(2)}%
                      </td>
                      <td className="num" style={{ 
                        fontWeight: 700,
                        color: isPositive ? 'var(--status-success)' : (isLoss ? 'var(--status-danger)' : 'var(--text-muted)')
                      }}>
                        {isLoss ? `-$${Math.abs(Math.round(a.EarnSaveLoss)).toLocaleString()}` : `$${Math.round(a.EarnSaveLoss).toLocaleString()}`}
                      </td>
                      <td className="num" style={{ fontWeight: 600 }}>{a.QualScore.toFixed(1)}</td>
                      <td>
                        {a.risk_flag?.includes('Outperforming') || a.risk_flag?.includes('Top') ? (
                          <span className="badge badge-success">{a.risk_flag}</span>
                        ) : a.risk_flag?.includes('Underperforming') || a.risk_flag?.includes('High') ? (
                          <span className="badge badge-danger">{a.risk_flag}</span>
                        ) : (
                          <span className="badge badge-neutral">{a.risk_flag || 'In Line'}</span>
                        )}
                      </td>
                      <td style={{ textAlign: 'center' }}>
                        <button 
                          className="btn btn-secondary" 
                          style={{ padding: '0.3rem 0.6rem', fontSize: '0.75rem' }}
                          onClick={(e) => {
                            e.stopPropagation();
                            onSelectAco(a.ACO_ID);
                          }}
                        >
                          Deep-Dive <ChevronRight size={14} />
                        </button>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}

        {/* Pagination Bar */}
        {acosData && acosData.total > pageSize && (
          <div className="pagination-bar">
            <span>
              Showing {((page - 1) * pageSize) + 1} - {Math.min(page * pageSize, acosData.total)} of {acosData.total} ACOs
            </span>
            <div className="pagination-controls">
              <button 
                className="btn btn-secondary" 
                disabled={page <= 1}
                onClick={() => setPage(page - 1)}
              >
                Previous
              </button>
              <button 
                className="btn btn-secondary"
                disabled={page * pageSize >= acosData.total}
                onClick={() => setPage(page + 1)}
              >
                Next
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
